### PR TITLE
Add PutObjectAcl versions to standard IAM S3 policies.

### PR DESCRIPTION
**Pull request by blever**
@markhibberd As discussed. I couldn't find any tests anywhere - am I looking in the wrong spot?

### CODE REVIEW

**Comment by markhibberd** [comment]
For policy stuff - https://github.com/ambiata/saws/blob/master/saws-testing/src/test/scala/com/ambiata/saws/iam/RolePolicySpec.scala

**Comment by blever** [comment]
Something I did just notice, since "saws" has gone public, this might be an issue - https://github.com/ambiata/saws/blob/master/saws-testing/src/test/scala/com/ambiata/saws/iam/RolePolicySpec.scala#L77.

**Comment by blever** [comment]
@markhibberd this is ready

**Comment by markhibberd** [comment]
:+1:  Need to get rid of that box though. Will add it as something for someone to do next week.

**Pull request merged**
