### PR TITLE
Add PutObjectAcl versions to standard IAM S3 policies.

### PR DESCRIPTION
**Pull request by blever**
Take 2. I suspect there is something wrong with CI at the moment.

### CODE REVIEW

**Comment by markhibberd** [comment]
These tests run as a part of integration suite which takes longer - not the normal saws test suite - is that what you mean?

**Comment by blever** [comment]
I meant https://ci.ambiata.com/job/saws/125/ and https://ci.ambiata.com/job/saws/126/.

**Comment by markhibberd** [comment]
Mmmm, looks like a flakey spec perhaps. Green now.

**Comment by blever** [comment]
Just go ahead and merge?

**Comment by markhibberd** [comment]
Yeh.

**Pull request merged**
