### PR TITLE
Use saws-aws build with AWS SDK 1.10.26

### PR DESCRIPTION
**Pull request by phickey**
@nhibberd - what further test stages are required?

### CODE REVIEW

**Comment by nhibberd** [comment]
I think this needs to be tested with notion + view. Possibly ivory(?) @raronson

**Comment by nhibberd** [comment]
Probably `tarski` as well

**Comment by nhibberd** [comment]
This needs a branches build on ci. None of the aws test run on travis

**Comment by phickey** [comment]
CI build for `saws.branches` [added](https://ci.ambiata.com/job/saws.branches/)

Merging on verbal :+1: from @markhibberd

**Pull request merged**
